sudo: false
language: node_js
node_js:
 - 'node'
 - 8
script:
 - npm run lint
 - npm run style-lint
 - npm run build:prod

jobs:
  include:
    stage: Deploy
    script:
      - npm run lint
      - npm run style-lint
      - npm run build:prod
    deploy:
      provider: heroku
      api_key:
        secure: KizpLvPdXBalrz8bzlndVQ
      skip_cleanup: true
